
2020-05-30 18:36:58,798 INFO: errors [in C:\Users\modop\Google Drive\PycharmProjects\Fyyur\app.py:517]
2020-05-30 18:36:58,821 INFO: errors [in C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py:517]
2020-05-30 18:36:58,821 INFO: errors [in C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py:517]
2020-05-30 18:37:03,609 ERROR: Exception on /venues/create [GET] [in C:\Users\modop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\modop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py", line 195, in create_venue_form
    form = VenueForm()
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-05-30 18:37:03,609 ERROR: Exception on /venues/create [GET] [in C:\Users\modop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\modop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py", line 195, in create_venue_form
    form = VenueForm()
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-05-30 18:38:23,156 INFO: errors [in C:\Users\modop\Google Drive\PycharmProjects\Fyyur\app.py:517]
2020-05-30 18:38:23,173 INFO: errors [in C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py:517]
2020-05-30 18:38:23,173 INFO: errors [in C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py:517]
2020-05-30 18:38:25,765 ERROR: Exception on /venues/create [GET] [in C:\Users\modop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\modop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py", line 195, in create_venue_form
    form = VenueForm()
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-05-30 18:38:25,765 ERROR: Exception on /venues/create [GET] [in C:\Users\modop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\modop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py", line 195, in create_venue_form
    form = VenueForm()
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-05-30 18:40:12,958 ERROR: Exception on /artists/create [GET] [in C:\Users\modop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\modop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py", line 414, in create_artist_form
    form = ArtistForm()
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-05-30 18:40:12,958 ERROR: Exception on /artists/create [GET] [in C:\Users\modop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\modop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py", line 414, in create_artist_form
    form = ArtistForm()
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-05-30 18:40:14,942 ERROR: Exception on /venues/create [GET] [in C:\Users\modop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\modop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py", line 195, in create_venue_form
    form = VenueForm()
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-05-30 18:40:14,942 ERROR: Exception on /venues/create [GET] [in C:\Users\modop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\modop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py", line 195, in create_venue_form
    form = VenueForm()
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-05-30 18:41:38,913 INFO: errors [in C:\Users\modop\Google Drive\PycharmProjects\Fyyur\app.py:517]
2020-05-30 18:41:38,931 INFO: errors [in C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py:517]
2020-05-30 18:41:38,931 INFO: errors [in C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py:517]
2020-05-30 18:41:40,649 ERROR: Exception on /venues/create [GET] [in C:\Users\modop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\modop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py", line 195, in create_venue_form
    form = VenueForm()
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-05-30 18:41:40,649 ERROR: Exception on /venues/create [GET] [in C:\Users\modop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\modop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\modop\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/modop/Google Drive/PycharmProjects/Fyyur/app.py", line 195, in create_venue_form
    form = VenueForm()
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\modop\venv\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\modop\venv\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
